### ISSUE TITLE
How can I train this model?

### ISSUE THREAD

**Issue by John-666-git** [XuanhaoLiu/TS-STDN#1]
Thank you very much for sharing the code. 
I encountered some issues when I wanted to train the model. I'm not sure how to train this model, and I don't know how to use the x_denoise and y_denoise that the model returns. I couldn't find the training code on GitHub. Could you please share the code for the training of this model? I would greatly appreciate it.
I sincerely hope to get your guidance. Warm regards, and thank you for your attention to this matter.

**Comment by XuanhaoLiu** [comment]
Hello, I have added the training example code in ReadMe, hope it can fix your question.

**Comment by XuanhaoLiu** [comment]
Don't see the variable name in the model. The outputs of TS-STDN are basically "label, reconstruction data in temporal domain, and reconstruction data in spectral domain".

**Comment by John-666-git** [comment]
Thank you so much for your helpful response! I really appreciate the time you took to address my questions.
